(function(){
'use strict';
var TAG='com-sbl-instruments-m-competition-v4-styling';if(customElements.get(TAG))return;
var TEXTS={leftLabel:'Lewy — opis',leftUnit:'Lewy — jednostka',rightLabel:'Prawy — opis',rightUnit:'Prawy — jednostka',centerLabel:'Środek — opis',centerUnit:'Środek — jednostka',fuelLabel:'Mały lewy — opis (bez ikony)',fuelUnit:'Mały lewy — jednostka',tempLabel:'Mały prawy — opis (bez ikony)',tempUnit:'Mały prawy — jednostka',footerPeriodLabel:'Stopka — opis okresu',footerPeriodValue:'Stopka — okres',footerPlanLabel:'Stopka — opis planu',footerPlanValue:'Stopka — wartość planu',footerDiffLabel:'Stopka — opis odchylenia',footerDiffValue:'Stopka — wartość odchylenia',footerDeltaLabel:'Stopka — opis zmiany',footerDeltaValue:'Stopka — wartość zmiany',footerUpdateLabel:'Stopka — opis aktualizacji',footerUpdateValue:'Stopka — data',headerText:'Górny tytuł',modeText:'Podpis trybu',topStatusText:'Górny status',arrowText:'Symbol centralny'};
var COLORS={frameDark:['Górna ramka','#0a0d12'],frameDeep:['Obudowa (cień)','#000104'],glassBlack:['Czerń tarczy','#05070d'],footerDeep:['Cień stopki','#05070e'],statusShell:['Panel statusu','#06070b'],statusInset:['Tło statusu','#030207'],blueFace:['Płaszczyzna lewa','#0e1725'],redFace:['Płaszczyzna prawa','#0e101d'],scaleOutline:['Kontur cyfr skali','#10141d'],statusEdge:['Obramowanie statusu','#151a25'],rimMid:['Obrzeże jasne','#cad6e6'],rimLow:['Obrzeże przygaszone','#9eaac3'],logoMetal:['Litera logo','#f0f2f4'],rimHigh:['Obrzeże białe','#ffffff'],accentText:['Biel napisów','#f4f7ff'],background:['Tło','#020307'],bezel:['Obudowa','#0c121f'],dialFill:['Tarcza — ciemna','#0b111d'],dialFillAlt:['Tarcza — jasna','#131e30'],dialBorder:['Ramki tarcz','#3c4a5e'],tick:['Kreski główne','#e8ecf2'],tickMinor:['Kreski pomocnicze','#8591a3'],leftAccent:['Niebieski akcent','#227ce5'],rightAccent:['Czerwony akcent','#fa263d'],redZone:['Czerwona strefa','#f32540'],yellowZone:['Żółta strefa','#ffca36'],leftProgress:['Postęp lewy','#31a4fc'],rightProgress:['Postęp prawy','#ff2946'],smallLeftProgress:['Postęp mały lewy','#f63a52'],smallRightProgress:['Postęp mały prawy','#df3942'],smallBase:['Podkład małych','#243147'],centerOutline:['Obramowanie KPI','#99a4b6'],footerLine:['Linie stopki','#3b4658'],navigation:['Nawigacja','#ed2646'],status:['Górny status','#ed2bb5'],logoFallback1:['Logo pasek I','#52bbeb'],logoFallback2:['Logo pasek II','#1554ac'],logoFallback3:['Logo pasek III','#eb3c51'],footerBackground:['Stopka — tło','#0b111d'],surfaceGlow:['Poświata','#153967']};
var FONTS=['scaleLeft','scaleRight','scaleFuel','scaleTemp','leftLabel','leftValue','leftUnit','rightLabel','rightValue','rightUnit','centerLabel','centerValue','centerUnit','fuelLabel','fuelValue','fuelUnit','tempLabel','tempValue','tempUnit','footerPeriodLabel','footerPeriodValue','footerPlanLabel','footerPlanValue','footerDiffLabel','footerDiffValue','footerDeltaLabel','footerDeltaValue','footerUpdateLabel','footerUpdateValue','headerText','modeText','topStatusText','arrowText'];
var SIZE={scaleLeft:30,scaleRight:33,scaleFuel:21,scaleTemp:21,leftLabel:24,leftValue:82,leftUnit:28,rightLabel:24,rightValue:82,rightUnit:28,centerLabel:24,centerValue:81,centerUnit:49,fuelLabel:17,fuelValue:21,fuelUnit:15,tempLabel:17,tempValue:21,tempUnit:15,footerPeriodLabel:21,footerPeriodValue:21,footerPlanLabel:21,footerPlanValue:21,footerDiffLabel:21,footerDiffValue:21,footerDeltaLabel:21,footerDeltaValue:21,footerUpdateLabel:21,footerUpdateValue:21,headerText:20,modeText:18,topStatusText:16,arrowText:40};
var FONT_COL={footerDeltaLabel:'#ff354a',footerDeltaValue:'#fd4150',modeText:'#ff354a',topStatusText:'#ff2aba',arrowText:'#ff2b43'};
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
function parsed(v){try{return JSON.parse(v||'{}')||{};}catch(e){return {};}}
function prop(k,l,t,more){return'<label><span>'+esc(l)+'</span><input data-prop="'+k+'" type="'+(t||'text')+'" '+(more||'')+'></label>';}
class Builder extends HTMLElement{
 constructor(){super();this._p={};this.attachShadow({mode:'open'});this._started=false;}
 connectedCallback(){this._render();}
 onCustomWidgetBeforeUpdate(changed){Object.assign(this._p,changed||{});}
 onCustomWidgetAfterUpdate(changed){Object.assign(this._p,changed||{});this._render();}
 _emit(p){Object.assign(this._p,p);this.dispatchEvent(new CustomEvent('propertiesChanged',{detail:{properties:p}}));}
 _render(){var that=this,p=this._p,colors=parsed(p.colorConfig),fonts=parsed(p.fontConfig),h='';
 h+='<style>:host{display:block;box-sizing:border-box;background:#111724;color:#e9effb;font:13px Arial,Helvetica,sans-serif;padding:11px}details{border:1px solid #303b50;border-radius:6px;margin-bottom:9px;overflow:hidden}summary{cursor:pointer;background:#1b2639;padding:11px;font-weight:bold}section{padding:11px}label{display:flex;flex-flow:column;gap:5px;margin:0 0 10px}input,select{width:100%;min-height:31px;box-sizing:border-box;border:1px solid #45536b;background:#101c2a;color:#eaf1ff;border-radius:4px;padding:5px}input[type=color]{padding:2px;max-width:90px;height:32px}input[type=checkbox]{width:17px;min-height:17px}input[type=file]{font-size:11px}h3{font-size:16px;margin:4px 0 10px}small{color:#9eacc2}h4{margin:10px 0 8px;color:#9ecffa}.triplet{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.triplet label{font-size:11px}.group{padding:8px;border-bottom:1px solid #273348}.half{display:grid;grid-template-columns:1fr 1fr;gap:7px}button{background:#2271ad;color:white;border:0;border-radius:4px;padding:8px 11px;cursor:pointer}</style>';
 h+='<h3>M Competition Cockpit v4 — styl</h3><small>Ustawienia są zapisywane jako właściwości widgetu SAC. Kliknij sekcję, aby rozwinąć.</small>';
 h+='<details open><summary>5 liczników — zakresy i wartości</summary><section>';
 [['left','Duży lewy'],['right','Duży prawy'],['center','Środkowy'],['fuel','Mały lewy'],['temp','Mały prawy']].forEach(function(x){h+='<h4>'+x[1]+'</h4><div class="triplet">'+([['Value','Wartość'],['Min','Minimum'],['Max','Maksimum'],['Precision','Dziesiętne']].concat((x[0]==='left'||x[0]==='right')?[['Ticks','Podziałki skali']]:[])).map(function(a){return prop(x[0]+a[0],a[1],'number','step="any"');}).join('')+'</div>';});h+='</section></details>';
 h+='<details><summary>Wszystkie napisy</summary><section>'+Object.keys(TEXTS).map(function(k){return prop(k,TEXTS[k]);}).join('')+'</section></details>';
 h+='<details><summary>Wszystkie kolory</summary><section>'+Object.keys(COLORS).map(function(k){return '<label><span>'+COLORS[k][0]+'</span><input type="color" data-color="'+k+'" value="'+esc(colors[k]||COLORS[k][1])+'"></label>';}).join('')+'</section></details>';
 h+='<details><summary>Czcionki – osobny krój, rozmiar i kolor</summary><section><small>Każda pozycja tekstowa, w tym numery skal, ma własne ustawienia. Dopuszczalne fonty zależą od przeglądarki/SAC.</small>';
 FONTS.forEach(function(k){var f=fonts[k]||{};h+='<div class="group"><b>'+esc(TEXTS[k]||k)+'</b><div class="triplet"><label>Krój<input data-font="'+k+'" data-field="family" value="'+esc(f.family||'Arial, Helvetica, sans-serif')+'"></label><label>Rozmiar px<input type="number" data-font="'+k+'" data-field="size" min="7" max="140" value="'+esc(f.size||SIZE[k])+'"></label><label>Kolor<input type="color" data-font="'+k+'" data-field="color" value="'+esc(f.color||FONT_COL[k]||'#ffffff')+'"></label></div></div>';});h+='</section></details>';
 h+='<details><summary>Logo – URL lub plik graficzny</summary><section>'+prop('logoUrl','Adres HTTPS obrazka lub data URI')+prop('logoWidth','Szerokość w układzie SVG','number')+prop('logoHeight','Wysokość w układzie SVG','number')+prop('logoVisible','Pokazuj logo','checkbox')+'<label>Wczytaj PNG/JPG/WebP/SVG (zapis jako data URI)<input type="file" id="local-logo" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label><small>Do publikacji zalecany jest plik na serwerze HTTPS. Obraz wgrany z dysku jest kodowany base64 i zwiększa rozmiar właściwości SAC. Limit: 200 KB.</small></section></details>';
 h+='<details><summary>Ładowanie, animacja, dane SAC</summary><section><label>Tryb danych<select data-prop="loadingMode"><option value="auto">auto — binding SAC</option><option value="manual">manual — skrypty beginLoading/finishLoading</option></select></label>'+prop('previewValues','Pokaż demo bez źródła danych','checkbox')+prop('animationMs','Rozświetlanie (ms)','number')+prop('animationOnRefresh','Powtórz animację po nowym zestawie danych','checkbox')+prop('enableBinding','Użyj binding SAC','checkbox')+prop('textureOpacity','Intensywność faktury kokpitu (0..1)','number','min="0" max="1" step="0.05"')+prop('showNeedles','Znaczniki aktualnego poziomu','checkbox')+prop('showBottomBar','Pokaż stopkę','checkbox')+prop('showMiniValues','Pokazuj wartości wewnątrz małych tarcz','checkbox')+prop('dataMeasureOrder','Mapowanie miar (oddzielone przecinkami)')+'</section></details>';
 this.shadowRoot.innerHTML=h;
 Array.prototype.forEach.call(this.shadowRoot.querySelectorAll('[data-prop]'),function(el){var k=el.getAttribute('data-prop');if(el.type==='checkbox')el.checked=p[k]===undefined?(k!=='previewValues'&&k!=='showMiniValues'):!!p[k];else if(el.value!==undefined&&p[k]!==undefined)el.value=p[k];el.addEventListener('change',function(){var v=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;var o={};o[k]=v;that._emit(o);});});
 Array.prototype.forEach.call(this.shadowRoot.querySelectorAll('[data-color]'),function(el){el.addEventListener('change',function(){var conf=parsed(that._p.colorConfig),k=el.getAttribute('data-color');conf[k]=el.value;that._emit({colorConfig:JSON.stringify(conf)});});});
 Array.prototype.forEach.call(this.shadowRoot.querySelectorAll('[data-font]'),function(el){el.addEventListener('change',function(){var conf=parsed(that._p.fontConfig),k=el.getAttribute('data-font'),field=el.getAttribute('data-field');if(!conf[k])conf[k]={};conf[k][field]=field==='size'?Number(el.value):el.value;that._emit({fontConfig:JSON.stringify(conf)});});});
 var file=this.shadowRoot.querySelector('#local-logo');file.addEventListener('change',function(){if(!file.files||!file.files[0])return;var f=file.files[0],accepted=['image/png','image/jpeg','image/webp','image/svg+xml'];if(accepted.indexOf(f.type)<0||f.size>200*1024){alert('Wybierz obraz PNG/JPEG/WebP/SVG do 200 KB.');return;}var reader=new FileReader();reader.onload=function(){that._emit({logoUrl:String(reader.result)});var e=that.shadowRoot.querySelector('[data-prop=logoUrl]');if(e)e.value='[obraz zapisany jako data URI]';};reader.readAsDataURL(f);});
 }
}
customElements.define(TAG,Builder);
})();
